### PR TITLE
Mobilize All Workers from Building

### PR DESCRIPTION
**Pull request by sraboy**
Based on https://www.7kfans.com/forums/viewtopic.php?f=17&t=112&p=5673#p5673

### CODE REVIEW

**Comment by MicroVirus** [comment]
Nice, thanks for the work! I'm looking forward to testing this/seeing it in action after the weekend.

On a side note, the team_id / team_info / TeamInfo is such a total mess, typically being half-set, half not set, reused for a different team but the existing team-members not being updated, etc. Your code also sets a team without setting the leader unit recno, which I don't think was ever intended, but I think it'll work just the same. If we're ever going to 'fix' the quirks related to mobilize-as-a-team, we're going to have to give a team its own proper class.

**Comment by sraboy** [comment]
Yeah, I wasn't exactly sure about that. I figured I'd leave it in in case there were some dependencies on it that I couldn't see; I think the idea was because the original code did set a leader but that didn't seem necessary for workers.

Either way, I agree that we could use a team class.

**Comment by the3dfxdude** [comment]
A few things.

1. In FirmMine, the mobilize button is drawn under the spy button. It is also one pixel off in y. Should be:
button_vacate_firm.paint(INFO_X1, INFO_Y1 + 249, 'A', "RECRUIT");

2. Multiplayer: mobilize_all_worker calls mobilize_worker, which sends the MSG_FIRM_MO
BL_WORKER. It doesn't seem to be processed on the receiver. The handler needs checked.

3. Clicking the mobilize button does select the workers, but nothing shows up in "Info". It's a bit disorienting. While you aren't picking a team leader, since there is not really one, FirmBase does have an overseer. And in the event that there isn't an overseer, you might want to do something to have Info display the selected people. See how the bounding box selection works here. Could fix Info.

4. After clicking mobilize, and while you do have selected units and can right click on a building, the cursor actually does not turn into an arrow. Might be Info related.

**Comment by the3dfxdude** [comment]
So actually, on a Seat of Power, you aren't actually ejecting the overseer. Not sure if this should be the behavior.

Finally, it seems like all workers and soldiers can enter any other building or fort, except the seat of power. Yes, soldiers can cross over to be workers accidentally. This seems like it should be prevented. For the seat of power, only civilians and generals can enter the building, which is more appropriate. However a spy should be able to enter any building having any occupation, if he wants to ;) (spy prevented on a seat of power if has an occupation already)

**Comment by sraboy** [comment]
Thanks for the notes. I'll try to take care of these in a couple days.

**Comment by sraboy** [comment]
I'm not following you on the multiplayer thing. I've actually never even used the multiplayer, never mind playing with the code, so I'm gonna need some help on that one. Working on the others.

**Comment by MicroVirus** [comment]
I've addressed the final issues with this code in pull #62; it should be ready for merger after this.

On the Seat of Power, I think we should keep it without the overseer -- this'll keep it consistent with other buildings and it doesn't really matter either way.

On units of profession X entering a building with profession Y, it's a good feature to have. It can be harmful at times, for instance when ordering your soldiers into a factory accidentally, but that's just something you shouldn't be doing :P. On the other hand, I find it useful to be able to recommission units of different professions, without first having to settle them in a town and then recruiting again. Anyhow, this issue is more general and does not specifically have to do with mobilising workers -- if we feel it needs reviewing, we could ask the community for input on the forums.

**Comment by sraboy** [comment]
No worries @MicroVirus. I've been pretty busy myself lately so I haven't been able to spend any time on this. Thanks for the fixes! Closing in favor of #62.

**Pull request closed without merging**
