### PR TITLE
Manual reorganisation

### PR DESCRIPTION
**Pull request by J-Moravec**
By moving assets to a separate folder, a clearer distinction is made between figures and tex files. Additionally, latexmkrc was added so that the manual can me easily compiled by running a single command `latexmk` (after latexmk program is installed). Finally, there was a strange non-standard space symbol that created some problems after compilation. There seems to be no reason keeping this symbol so it was substituted by the standard space symbol.

### CODE REVIEW

**Comment by J-Moravec** [comment]
Depending on the structure of the manual, I would suggest even more drastic reorganisation of figures into their separate folders according to type, but this should already help a great deal.

Another way to do it would be to have each chapter in a separate folder (with their own personal figures, tables and so on).

**Comment by the3dfxdude** [comment]
I think splitting by chapter makes the most sense.

**Comment by raz0rknaif** [comment]
When running latexmk with the Makefile, it does not compile the index with the large letters separating the index entries. Also, I would like the manual to be outputted to 7kaa_manual.

**Comment by raz0rknaif** [comment]
the3dfxdude, please restrict this PR to adding the folder(s) for the graphics (with the addition to main.tex) and adding the Makefile. I have too many changes to the .tex files for your master branch to be developed on top of. The spacing changes are okay, too.

**Comment by the3dfxdude** [comment]
Loki,

You should publish your branch and put everything you need changed there. Then work with Colombo to know how to do the migration. That way Colombo can see your changes.

**Comment by raz0rknaif** [comment]
I can certainly publish my changes. It is not much; I have primarily restored the graphic sizes, and the manual is looking much better, and everything is cooperating even more so since restoring the original paper size.

Now, I am working to restore the boxes and tables (also removing the tables I used initially for simplicity) among other minor changes such as consistency in using bold typeface and the manner which keyboard keys are displayed (i.e. 'J', bold typeface, <Enter>, etc.).

**Comment by J-Moravec** [comment]
@the3dfxdude @raz0rknaif Rebased the changed into a current master and added a few minute additions (files used spaces and tabs in similar places, so I tried to unify it a bit). I am not sure about the apostrophe symbol (or single quote mark), but the one that was there was not rendering properly anyway.

**Comment by J-Moravec** [comment]
On multiple places (especially in tables) both tabs and spaces were used. This introduced inconsistency. Given that previously there was a problem with yet another whitespace symbol that was also rendered incorrectly, then I think the best course of action is to replace all whitespaces with standard space.

**Pull request merged**
