### PR TITLE
HD fork require a code merge

### PR DESCRIPTION
**Pull request by starportx**
New features:
1. Configurable HD mode
2. New HD resource for SD768/HD1080
3. Scalable blit
4. Some hotkey modification

1. Configurable HD mode
	Instead of using constant macro VGA_WIDTH as resolution params, new function config.init_resolution()[AM.cpp] will read /data/config.ini file to initiate 
the resolution parameter, and #define VGA_WIDTH config.win_width, other classes use this macro to adapte differenet resolution.

2. New HD resource for SD768/HD1080
	Create .res file for two resolution modes(I_IF_hd2.res for SD768, _hd3.res for HD1080), with modified sraboy/skaa_editor.
	
3. Scalable blit
	Simple modified blit function IMGblt3()
	
4. Some hotkey modification
	Some hotkey customization in OMOUSECR.cpp, no need to pull to master.

### CODE REVIEW

**Comment by sraboy** [comment]
@the3dfxdude Minor nitpick: can we eliminate macros like `#define` wherever we're refactoring code anyway? The project now requires C++11, so we should take advantage of strong typing constants when possible.

@starportx For me, every `OptionInfo` assignment needs to be updated to explicitly cast to `short` due to a narrowing conversion error. Also, here's what happens when I launch on macOS with any resolution:

hd

**Comment by the3dfxdude** [comment]
sraboy,

If you are asking if we can properly type constants in a general sense -- yes that can be something addressed in a different pull request.

As far as what's being added here with #define, that's not going to get in, I suspect.

**Comment by the3dfxdude** [comment]
So you understand what I am thinking. I have already made plans how to implement this. The first step was to create a way to expose additional "config" variables (addresses another request too). Then I was going to create a couple of resource files to store necessary data for different aspect ratios, taking some inspiration from 7k2. Finally we can start repositioning and consider adding graphics to fill in UI gaps, which may be phased in on need and type.

With what was done here, it looks like I'd have to redo it anyway. I think I'd rather keep what we have and work in something similar to 7k2 step by step. I could use this as some hint, but considering 7k2 already did the work, I don't think there is much to add from this.

**Comment by starportx** [comment]
Thanks for reply guys. @the3dfxdude I start this branch just for my own desire of HD version, and request a pull by the way if you dont have a HD plan, now it looks not neccesary. Hope I can play "offical" HD asap. :)
@sraboy I dont have mac, only tested on pc and linux with vmware

**Comment by the3dfxdude** [comment]
Thank you for your review of some of the basic graphics code. I have opened up a topic here:
https://7kfans.com/forums/viewtopic.php?f=20&t=1291

I will be winding down github as I no longer wish to use it. Our sourceforge page has been active for a while, and I'm opening to using the resources there.

**Pull request closed without merging**
