### PR TITLE
AI improvements and fixes

### PR DESCRIPTION
**Pull request by MicroVirus**
Fixed various bugs with AI reasoning.
Optimised some of the AI logic.

Added hotkeys for Market, Harbour, Transports, and Inn.

### CODE REVIEW

**Comment by MicroVirus** [comment]
> I don't like this change. There is a preference for finding a town meeting the criteria with the lowest resistance (done by sorting), and this has been removed.

I'm not quire sure I follow. The sorting is still in there, via `std::priority_queue` using `std::less` which uses `CaptureTown::operator<`. I only refactored to a non-static list, and chose priority queue, because of the expected use.

> But you don't need to make a second list at all. I think you can loop through all independent towns once, identifying if it meets all the criteria, and has lower resistance than the last one found. At the end of the loop, if you have a town recno, you finish with adding the action. It will taking refactoring this function, start_capture(), and capture_build_firm(). Correct me if I am wrong.

I was thinking this too, initially, but as far as I can tell you do need (or maybe: want) the sorted list. This is because `start_capture` may fail for the 'best' town but work for one of the other towns. It shouldn't be very likely, but can happen, for instance because there is no neighbour space, There's also some odd reasoning (that I think is wrong) with `should_use_cash_to_capture`.
We could move all these things ahead into the initial loop, but then we'd be doing a lot of extra processing upfront for potentially every town in the list (if they happen to be inversely sorted) that is actually only required for the one town we will capture. I've already added some changes that at least reuse part of the `capture_expected_resistance/find_best_capturer` work.
I figured the cost of the list is less than the cost of all the additional processing.

**Comment by the3dfxdude** [comment]
Yes, I missed the subtle change by using a priority queue. That means the change should be a no-op for logic and that means it is good enough to fix the potential crash. The other comments are applicable to optimizing the code, which could be done at a different time.

**Comment by the3dfxdude** [comment]
New warning:

OAI_CAPT.cpp: In member function 'int Nation::think_capture_independent()':
OAI_CAPT.cpp:145:26: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
    captureTownQueue.push({townRecno, minResistance, captureUnitRecno});
                          ^
OAI_CAPT.cpp:145:70: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
    captureTownQueue.push({townRecno, minResistance, captureUnitRecno});

I don't feel like opening the door to this. I was ok with making the code base ISO C++ compliant, but this might not be a good idea right now.

**Comment by MicroVirus** [comment]
We are not going for C++11 support? I figured, since we have a decent build system that supports multiple compilers and even older versions of GCC support most C++11 features that we'd move along.

**Comment by the3dfxdude** [comment]
I'm not sure what you mean by going for C++11 support. Could be two aspects.

1) Using C++11 extensions, as you have in this pull, means that we can only support compliant compilers. C++11 is still fairly new, and it's hard to know how much I can really use with what's out there. So this is the compatibility concern.

2) Generally with a standard update, there are deprecations. We ended up having to adopt ISO C++ at a minimum, since there really weren't any pre-ISO compilers anymore. 7K used deprecated syntax, this led to not so fun labor, but we probably got important bugs fixed. I don't see a need to become compliant if in this case, there are required changes.

So my first thought is to decide if we need to set the compiler switch if we use any new syntax. The answer is probably not. No compiler we use today absolutely requires it at minimum, so we don't really require any checking features.

I could not determine if deprecations occurred in C++11, so I think I'd have to try the switch out to learn more. So if we are going to throw the switch, I think it will be at the same time we pull the source code into compliance.

Now about the compatibility. I only run Visual Studio 2005, because that is what I have, and that is too old. Later free versions that support C++11 need Windows 7 or later and I don't have that. (* well, actually I do at work but...). So at least for me, pulling this means I'm not going to support Visual Studio for the time being, since I have no plans to purchase Windows. I think I'd leave VS up to you.

So going back to the compatibility question. I think that one needs solved. I will check when GCC implemented compliance with the spec, and get a rough estimate what distros/mingw/Mac platforms ship with, and see how far back it goes. I suspect it'd be hard to go back more than 3 years, unfortunately, which will be pretty similar to VS. Then rough-gauge that merging this code will cause any complaints.

**Comment by the3dfxdude** [comment]
Just general report here.

The three compilers, VS, gcc, and llvm all stated compliance in mid-2013. Likely for a long time, most extensions were supported.

I'm not going to enable syntax checking and bring the code base into whatever is considered C++11 compliant. I don't think it is worth it. However, gcc6 did this:
The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98
So we'll have to watch out for that.

As far as linux distros, I don't think we'll have much of an issue. For Ubuntu, they should have the C++11 compliant compiler in the current supported versions from here on out.

I'll likely have to update my mingw installation.

So if it works for you or me, we'll go forward with it. Even if gcc gives a warning.

**Comment by MicroVirus** [comment]
> Now about the compatibility. I only run Visual Studio 2005, because that is what I have, and that is too old. Later free versions that support C++11 need Windows 7 or later and I don't have that. (* well, actually I do at work but...). So at least for me, pulling this means I'm not going to support Visual Studio for the time being, since I have no plans to purchase Windows. I think I'd leave VS up to you.

Yeah, I can cover the VS part. Mostly, if it compiles for GCC then it compiles for VS, the only exceptions being when POSIX functions and headers are concerned.

What I'm wanting in terms of C++11 support is to be able to use some of the new features (language and library), as they constitute great improvements to the language.
I don't think much was deprecated, but we can tackle it if and when the compilers start complaining as far as I'm concerned -- so far, there's just some warnings about [user defined literals](http://en.cppreference.com/w/cpp/language/user_literal) when a string literal is directly followed by a non-whitespace character.

**Pull request merged**
