### PR TITLE
Add index style file

### PR DESCRIPTION
**Pull request by raz0rknaif**
Initial index commit
Compiled with makeindex -s simpleidx.ist %.idx

### CODE REVIEW

**Comment by raz0rknaif** [comment]
This PR was premature, and I apologize for that. I have made changes that display the index more nicely. I am considering closing this to submit the style file with the .tex files once I'm finished.

**Comment by raz0rknaif** [comment]
I pushed the newer index style file. You can go ahead and merge or close this PR as it may take a bit more time to push the completed .tex files as in addition to indexing, I am polishing up the manual due to small issues I have been aware of for some time.

**Comment by the3dfxdude** [comment]
I can't see an index. How do I build with this?

**Comment by the3dfxdude** [comment]
OK I figured it out.
makeindex -s simpleidx.ist main.idx

If you were suggesting you have a Makefile, you could send that in too.

**Comment by raz0rknaif** [comment]
I do not have a Makefile, and writing one is over my head.

**Pull request merged**
