### PR TITLE
Credit Translators and Remove Wiki References

### PR DESCRIPTION
**Pull request by W-Damian**
ř does not display in the manual after compiling.

### CODE REVIEW

**Comment by the3dfxdude** [comment]
The log file is saying that there is a missing character in the font used. I think the encoding is otherwise fine. You might want to ask him if he wants to be credited as Colombo instead.

**Comment by W-Damian** [comment]
Yes, I see that log entry now. I can ask him on Discord. So far, I have been using whatever information is public, which includes people's real names.

I might consider adding another font to support names foreign to English and the Latin alphabet, but at the moment the Universalis font being added would take precedent.

**Comment by W-Damian** [comment]
You can merge this PR if nothing is holding it back from your side.

**Comment by the3dfxdude** [comment]
The character is still missing unless I comment out the package for the main font.

**Comment by W-Damian** [comment]
Oh my mistake. It should be \u{r} not v.

**Pull request merged**
