### PR TITLE
Minor fixes November 2016

### PR DESCRIPTION
**Pull request by MicroVirus**
Various minor bugfixes and quality-of-life changes for debugging.

I looked at the output of a static code analysis tool and fixed some bugs and added `err_when` tracking to test if other issues it found occur.

I'm particularly proud of a very nasty crash I kept seeing and managed to finally fix in commit d6fa3c42b1

### CODE REVIEW

**Comment by the3dfxdude** [comment]
Comment for commit d6fa3c42b1e69f1b85789bd4799fd2cef850db18

7k2 may have the same bug.

Harbors need to be checked for a similar issue.

**Comment by the3dfxdude** [comment]
Comment on commit 64c057caa8e3824c0707df3265f41c6d4b6fe1fa

Your change is the correct one, since the function is not actually ai code, but unit action processing code.

I was thinking it might be a good idea to return feedback to the user, if the action was for the nation a human is controlling, with maybe a news entry or a sound like other RTS games would.

**Comment by MicroVirus** [comment]
> Comment for commit d6fa3c4 "Fixed crash with weapons from a War Factory after nation surrender."
> 7k2 may have the same bug.
It probably has, we should check. We maybe should also give 7k2 more attention in the build & build-system department. I know toaster got a long way into fixing 7k2 and he got a CMake build setup, which should work fine I think. I once started with porting some of the changes from 7kaa to 7k2, but I didn't get very far. It's also hard in some areas, because especially the AI action code has seen some serious changes (and I honestly don't understand the AI action code of either yet).


> Harbors need to be checked for a similar issue.
I don't think harbours exhibit the issue, because they only have one tech level of each unit. The issue is specifically with having a higher tech-level weapon in the queue for which the receiving nation has only a lower tech level.

**Comment by MicroVirus** [comment]
> Comment for commit 2dc54ba "Nation::ai_build_firm: Removed duplicate check for get_skilled_unit."

I agree that the logic isn't what it could be. The `find_skilled_unit` should probably be modified to also search for available construction workers. At the very least. the logic should be reviewed.
One thing with the MINING skill is that I think it'd be best for the AI to always use a miner, because this'll cause a town to be created with the mine at the right spot. I think the presence of the town kicks off some decent processing, which wouldn't all be present if the mine was built without a town. At the very least, the AI will take action faster I think, rather than first wait for the mine, then for the town, then market + factory + fort. At least this is the feeling I get from watching the AI.

**Pull request merged**
