### PR TITLE
README changes and an image upload

### PR DESCRIPTION
**Pull request by tmr83**
Hi, this pull request is not too important, but suddenly I need to focus on other things. So I am pushing these changes upstream so that they are not laying around somewhere. I tried to make the optional dependencies for building the game manual OS agnostic.

### CODE REVIEW

**Comment by tmr83** [comment]
If you want, I can add a simple Makefile and use Autoconf, but then latex.m4 would be required, and those macros are not in the autoconf-archive package on my distro.

**Comment by tmr83** [comment]
I was going to add a couple more images to this pull request when I noticed the file sizes were rather small compared to similar, older images. So please don't merge this until I sort them out.

**Comment by tmr83** [comment]
Quick question: is it possible to extract images from the .res files with deresx? I tried extracting them as .bmp, but my image viewer says, "BMP image has bogus header data."

**Comment by the3dfxdude** [comment]
If you have m4 scripts for autoconf, then we put them into the m4 directory. Integrating the doc is definitely something that should get done.

Extracting to bmp is possible. The files in the res archive are icn (unless it is a sprite). I should have an icnbmp.c source file somewhere.

**Comment by tmr83** [comment]
Please provide icnbmp.c if you have it.

I am using these macros fine: 

AC_PROG_LATEX
AC_PROG_PDFLATEX
AC_PROG_MAKEINDEX

Unfortunately, there isn't something like them for checking to see if LaTeX packages are installed. Or maybe I am not understanding AC_LATEX_PACKAGES.

**Comment by the3dfxdude** [comment]
I haven't heard about any font issue from the released doc, so I must have the proper texlive extra package?

It might be better to require the user to use --enable-doc, meaning the doc will not be enabled by default. I think the distro packagers can figure out what to do if it is documented as you have in the readme, plus mention the --enable-doc switch what that will do if they provide the requirements. For casual users, texlive is kind of a big ask, so it's better not to push it by default.

If you have how make works down, then it might just be implementing the variable and the conditional in the autotools files.

**Comment by the3dfxdude** [comment]
I send some code to your email to help on the images.

**Comment by the3dfxdude** [comment]
OK I merged in the README changes. Please send in a rebased pull request for the image file changes. Closing.

**Pull request closed without merging**
