### PR TITLE
doc/credits: align manual with main menu credits.

### PR DESCRIPTION
**Pull request by tmr83**

### CODE REVIEW

**Comment by the3dfxdude** [comment]
Should we update the in game credits instead?

**Comment by tmr83** [comment]
That's fine. I am a little bit uncomfortable with some of the names I included because they are not in the git log, but I know they helped with the Russian translation. And some Russian translators are listed as contributors on Github, but I used their real name because I knew them.

**Comment by the3dfxdude** [comment]
Ok, it's hard to know right now then how some might want to have the names credited. If this is better, then I will merge it.

**Comment by tmr83** [comment]
This commit is better for me because I am not too fond of the credits portion in the manual, and this way I do not have to decide who and how to credit people. But you are missing some people who have committed to the repo. It's not a secret that they committed to it. You could at lease omit Olya Kudryavtseva, Vlad Klevtsov, and Elena Zasutskaya.

**Comment by the3dfxdude** [comment]
Merged per recommendation to sync. Contributors can tell us how they want credited in game and manual. But all contributions are still to documented in the commit history.

**Pull request merged**
