### PR TITLE
Update manual with substituted fonts

### PR DESCRIPTION
**Pull request by raz0rknaif**
Restored gothic font.
Substituted Galliard font.

### CODE REVIEW

**Comment by raz0rknaif** [comment]
So, I will stop pushing to this PR now. Any other updates to the manual will be in another PR.

**Comment by the3dfxdude** [comment]
! LaTeX Error: File `accanthis.sty' not found.

**Comment by raz0rknaif** [comment]
I am aware the Accanthis font is an external dependency. I installed it in addition to Texlive-base on Debian. Please, install Accanthis from https://www.ctan.org/tex-archive/fonts/accanthis/ or from your Linux distribution's package repository to fix this issue.

**Comment by the3dfxdude** [comment]
Please point me to the gothic font, because I don't have that either.

**Comment by raz0rknaif** [comment]
yfonts (https://ctan.org/pkg/yfonts)

**Comment by the3dfxdude** [comment]
OK -- yuck. CTAN packages and how tex manages fonts is pretty bad for the casual person. Luckily texlive cleans it up with a ready to go version. So that makes our answer simple.

BTW, the accanthis font fits well with the game itself, and it's nice to see gothic letters too.

**Pull request closed without merging**
