### PR TITLE
add and improve German translations

### PR DESCRIPTION
**Pull request by zyrup**
During translation I had trouble with the grammatical gender, hence I tried to avoid gender defining words in some cases e.g: EN (Your «Firm» near «Town» has been ...) and in DE (Your) could be either (Ihr) or (Ihre) depending which gender «Firm» has.
Also I did not translate the texts for the tutorial. I suggest keeping the tutorial in English for now because the German translations there are not really understandable.

### CODE REVIEW

**Comment by raz0rknaif** [comment]
Question: why isn't the German translation of the tutorial text understandable?

**Comment by zyrup** [comment]
I assume google translator or something similar was used for the translation and it's not an accurate translation service.

**Comment by the3dfxdude** [comment]
For the messages you corrected, please remove the fuzzy flag, otherwise no one will see them. Unless you have a good reason for keeping them marked fuzzy.

**Comment by zyrup** [comment]
> Please mark the tutorial text as fuzzy then, and it will do as you are asking.

They were already marked as fuzzy. I left it that way now.

> The issue with gender based articles could be fixed. Do you think the text will have a better fluency if the article was included?

I would like to test this by playing through but afaik it is not possible yet to select a language for the game, right?

> For the messages you corrected, please remove the fuzzy flag, otherwise no one will see them. Unless you have a good reason for keeping them marked fuzzy.

I did so.

**Comment by the3dfxdude** [comment]
Add 'de' to the LINGUAS file, compile the game, install, then you will be able to use your system locale to start the game in german. You can add the LINGUAS file change to your pull request if you'd like.

**Comment by zyrup** [comment]
> Add 'de' to the LINGUAS file, compile the game, install, then you will be able to use your system locale to start the game in german. You can add the LINGUAS file change to your pull request if you'd like.

I ran into trouble compiling the game. Sorry I'm relatively new to this. When I run `./autogen.sh` .. `./configure` .. `make` I get a fatal error `'libintl.h' file not found`. I was not able to find this file and `locale.h` file in the repo.

**Comment by zyrup** [comment]
I managed to compile the game into german and noticed that umlaut characters such as äöü are displayed ''a ''o ''u which is incorrect. Maybe it has to do with unicode settings?

**Comment by the3dfxdude** [comment]
The umlauts look correct under my system using LANG=de_DE. Is your system restricting ASCII-only?

I want to merge the pull request, but I notice that your name and email address on the commit aren't correct. You ought to correct that, or tell me what to put in there.

Also BTW, are you running on MacOS? Maybe that's why you are being forced to an ASCII codeset.

**Comment by zyrup** [comment]
> The umlauts look correct under my system using LANG=de_DE. Is your system restricting ASCII-only?

> Also BTW, are you running on MacOS? Maybe that's why you are being forced to an ASCII codeset.

Yes I'm running on MacOS. After setting German as primary language in `System Preferences > Language and Region` the compiler used the correct codeset.

> I want to merge the pull request, but I notice that your name and email address on the commit aren't correct. You ought to correct that, or tell me what to put in there.
 
I'll adjust the name/email in the following commits because I'm planning to do some more adjustments. E.g. in the village screen population "Bevölkerung" overlaps with peasants so I'm planning on using some abbreviations.

**Comment by the3dfxdude** [comment]
So I have written code to allow wrapping of multiline column headings and to not spill over into the next column. The single line column headings can be done the same. I don't think we should force the text to be abbreviated in the translation database because it's more work than needed and rendering to screen is subject to change. We should just translate and adapt the interface the best we can.

Were you going to send in more? Also what about correcting the author line? Send me the appropriate information and I can get this in.

**Comment by zyrup** [comment]
What do you mean by hand edited? I did not run update-pot.

The lower notification log has problems with the German umlaut:
screen1

In some cases the texts can be too long:
screen2
screen3

Some things don't seem to be translateable at all, such as the whole menu. Also the date strings are translated in de.po but are not being compiled:
screen4
screen5

**Comment by the3dfxdude** [comment]
Thanks for the changes. I have merged the pull request into a single commit and pushed it.

To address the things you have raised:

- Umlauts: I don't have this problem. It seems like your system is forcing the encoding into multibyte UTF-8 incorrectly preferred by the system. The game is supposed to override the system's preference, but I guess it will only work if your iconv supports ISO-9660-1. For some reason it doesn't? Can you figure it out?
- Truncation for long text: I will need to think about these cases. The news should be fixable. I might also go ahead and give more space to that last column in the report screen. So I will handle these.
- Date strings for year and months: The pluralization needed changing and was done with this new version. Please pull my latest and clean up the fuzzy or address the new messages.

Unfortunately we had to change a bunch of messages to deal with ambiguities caused by the code. Many are fixed now, but it might take a few passes until we catch everything.

**Comment by zyrup** [comment]
- Umlauts: I've not figured it out yet.
- Date strings for year and months: Ok. I'll probably do further translations at some point.

I wonder if it is possible to adjust the single commit, because now my old account is given credit for the translations although I would have preferred this one.

**Comment by the3dfxdude** [comment]
No, I can't rewrite the commit history.

OK, well I went with the other account because it was used and it had an email address to identify you. The new account had commits under an invalid email. If you can fix your new account, maybe it will automatically change over to your new account.

**Pull request closed without merging**
