### PR TITLE
Added FreeDesktop.org shortcut and app store metadata

### PR DESCRIPTION
**Pull request by Mailaender**
Required for #183 and other Linux distribution packaging.

### CODE REVIEW

**Comment by the3dfxdude** [comment]
@lennyhans Please look at what would be proper integration for the desktop file into the Makefile that is not flatpak specific. I don't see a reason to merge in the flatpak app store meta data.

**Comment by lennyhans** [comment]
You mean generate the file?, it could be done, but I think that here the files are present to create a link between the flathub publication and the upstream package. It could be burdensome to maintain but there are pieces that can be glued to reduce the future work

**Comment by Mailaender** [comment]
The [Open Age Rating](https://hughsie.github.io/oars/) might need an update as I mostly guessed it.

**Comment by the3dfxdude** [comment]
@lennyhans Yes, I am looking for integration ideas. It does not have to be generated on the fly. If we don't use it, then we should not provide them. So just thinking about what to do.

@Mailaender I was reading about how the meta data file is used. What you provided might be sufficient for what is used by flathub or where ever flatpaks are distributed. It might not be sufficient for others. I read that Debian aggregates the files for apt. And they attempt to upstream further modifications for Debian. This is quite telling the state of appstream data: https://appstream.debian.org/sid/main/index.html   Ubuntu has different appstream results for the same(?) data. Also they seem to not actually need upstream to provide the files, and this is been true for a long time apparently.

I've long decided against providing unique files for packagers and their specific processes (especially if we don't use it), only to get each distro wanting to file change requests to the files to suit their purposes. Note rpm is a long time standard, but I noted differences between what distros did that warranted not even bothering. We aren't going to provide an app store or tweak the file for each variant of the standard. They can collect meta data and aggregate into their packaging system on their own. After reading what Debian wants for desktop or icon files, I don't want to start there either. Generating a file on the fly using Make might not be a bad idea, but since downstream managed on their own so far, I don't think we should start supporting them.

**Comment by Mailaender** [comment]
The metadata aggregation is different per distribution / packaging format. The source is the same. It also helps identify the software with a unique ID so GNOME Software or KDE Discover knows that the distribution package and the Flatpak are the same application just from different sources. Your argument that distributions might fight over it in your repository is not justified. The files are standardized and the ones I submitted passed the strict Flathub linter.

**Comment by lennyhans** [comment]
@Mailaender I think you're mostly correct, just mention that the application has never taken the "install-able" missing step, so provide a packaging relevant file (even if it is a standard and recommended way to describe an application) is unnecessary because packaging is not on the project scope.

@the3dfxdude I think that to take advantage of provide a .desktop file for linux distributions, a good approach could be to add an _install_ step on the _makefile_, so it copies the data, the music and create the graphical application entry, that way the desktop file can be helpful and it is not tied to some external package manager or packaging system, what Mailaender did provided is (almost) the minimal standard that a desktop file can have to provide a useful graphical direct access to the application (if we go beyond, it can get translated to provide insightful description)

by the way _thefreedesktop_ recommends add the metadata in some way to guide any appstream (even if it's not part of what the distribution that handles that package expect, they usually just apply their own patches)

**Comment by Mailaender** [comment]
First entry on https://www.7kfans.com/community.html is

> Development
[Building From Source](https://www.7kfans.com/community/Building-From-Source.html)

which isn't all that useful if you already installed it pre-compiled.

**Comment by Mailaender** [comment]
Please don't hesitate to replace it. After all, that is why this file should be maintained here.

**Comment by the3dfxdude** [comment]
@tmr83  Let's push possible flatpak suggestions through lennyhans. The links in the flatpak should just be merged into a single "7kfans.com" because the landing page should have navigation needed rather than track individual pages. The doc still needs autotools integration, and I would like to do other things that would not have to need pushing changes into this meta data.

**Comment by Mailaender** [comment]
> For the Flathub package, can you install the pdf like the music?

The players won't be able to open the PDF unless you integrate a PDF viewer into the game.

**Comment by Mailaender** [comment]
> Can the .desktop file also link to local documentation?

Please don't. These are reserved for applications.

**Comment by Mailaender** [comment]
I removed the link to the PDF now.

**Comment by the3dfxdude** [comment]
We will not add support for this in tree at this time. We have been using sourceforge for the main repository and release notification, so you might want to check on that. The github page may get archived.

**Pull request closed without merging**
