### PR TITLE
Add Esperanto translation

### PR DESCRIPTION
**Pull request by jorgesumle**
Only 27 of 1633 strings (1%) translated. I want to ask if this is the way I should submit translations to this project. If so, maybe you prefer that I mark this as WIP and open a new merge request when progress is 20% or something more significant. In any case, I want to tell you that I'm slowly but surely working on this translation.

### CODE REVIEW

**Comment by the3dfxdude** [comment]
You can send me a pull request, email the pull information, or email me a patch set.

**Comment by jorgesumle** [comment]
I'm making some progress. How can I test the translation in-game? I tried compiling it with the typical `./configure`, `make`, `make install`, but for some reason it still doesn't show in Esperanto. I changed the LANG and LANGUAGE environment variables to Esperanto.

**Comment by the3dfxdude** [comment]
I can merge now and enable the language in the build to make sure it works, but you still need to provide appropriate environment.

**Comment by jorgesumle** [comment]
OK, then I can test and submit another pull request when I finish translating.

**Comment by the3dfxdude** [comment]
Please remember to do these things when you test.
1) delete po/stamp-po
2) run make install to create a locale dir somewhere, since the default location is hardcoded from running configure, and it needs a certain directory structure
3) set SKLOCALE to the path of the base locale directory to override the hardcoded path if you are locally testing
i.e. SKLOCALE=/home/user/7kaa/share/locale

Another option is to copy the locale directory into $SKDATA/ but you still need to make install to create it somewhere.

**Pull request merged**
