### PR TITLE
Mobilize All Workers from Building [Multiplayer Fixed]

### PR DESCRIPTION
**Pull request by MicroVirus**
This is an update to pull #51. This fixes the issue with multiplayer not being handled, as well as the mouse 'squiggly' arrow / hover-feedback not being present. I've also removed the team code.

@sraboy Please check commit 0d6f990 to see if it is correct. You can also check the first, 9d62bb1, to see how multiplayer messages are implemented and used in Seven Kingdoms.

### CODE REVIEW

**Comment by MicroVirus** [comment]
I've finally glossed through all the team code and it seems that `team_id`, `leader_unit_recno` and `team_info` are all different concepts. Most importantly, it's fully possible to set `team_id` without a leader unit.

`team_id` only does *one thing*
- In OPOWER it makes sure that when you right-click a unit you get everyone with the same team id.
There is a commented-out `err_when` that verified that the leader unit (via `leader_unit_recno`) has the same `team_id`, but this already fails when you put the general back in the fort, which is probably why the check has been scrapped.

`leader_unit_recno` has a slight chance in meaning for nation and non-nation units:
- It indicates which unit is the leader (must be a general or king) of the group.
- For Fryhtan and Rebel units, the `leader_unit_recno` is the only thing that determines the team.
- For nation units, the leader holds a `team_info` which determines the team.
  - It is meant that this is one to one, so every unit that has `leader_unit_recno` set to X is in `X.team_info` and vice versa (every unit in `X.team_info` has `leader_unit_recno == X.sprite_recno`).
- Units that are led have a higher target loyalty.
- Units that are led gain a bonus to attack if the leader is near (either mobile or in a nearby Fort).
- The leader gains bonus leadership experience from the soldiers that he gives an attack bonus to as they earn experience.
- Units that are led betray along with the general.
- For AI, the leader will perform `think_normal_human_action` for the entire team.
- The AI will decommission units that fail certain actions, such as `think_normal_human_action` and seek-path fail, unless they have a leader.

About `team_info`:
- `FirmCamp::patrol` is the only function that creates a `team_info` team.
- All generals and kings have a `team_info != NULL` (allocated).
- All other units have `team_info == NULL` (unallocated).
- For Fryhtan and Rebel leaders, `team_info` is unused even though it's allocated; only `leader_unit_recno` is used.
- The current code handles this by looping through the entire `unit_array` and checking `leader_unit_recno`. Depending on the case, first `is_deleted` is checked or not; most often it is checked.
- Therefore, unless you can directly guarantee that the code only runs for nation units, you cannot use `team_info`.
- Members of the team are called to help if one of the team members is attacked.
- Members of the team stop chasing an enemy all at once.
- As an aside, the above two points explain why Fryhtans and Rebels don't help each other out (why they don't act as a team): the code uses/requires a proper `team_info`.
- The reason why Rebels and Fryhtans don't use `team_info`, I suspect, is because it's capped to 9 units max, and both may have more units in a team. For nation teams, the max is what you can get out of one Fort sortie, which is 8. Amusingly enough, the max value is 9 -- no clue why: the leader itself isn't part of the `team_info`.

There's some issues/confusion with this setup as soon as the leader is assigned to a fort.
- `FirmCamp::assign_overseer` (and `FirmBase`'s too) breaks the one-to-one of `leader_unit_recno` and `team_info` -- it just sets `team_info->member_count = 0` without updating the `leader_unit_recno` of the units.
  - A possible solution is to not touch the `team_info` at all; just like when the units are defending, the leader can lead the team from the fort if they are nearby enough.
- `FirmCamp::patrol` also breaks the one-to-one when patrolling the overseer when there are no soldiers in the fort. The code attempts to do the right thing (not break the team) but ends up breaking the team later in the function.
- The real question is if a team should stay totally intact if a general goes back into a fort.
  - Should look into how auto-defending forts handle this; also *if* it is handled properly.


Anyhow, the conclusion of this post for the matter at hand is that we are safe to use `team_id` for any UI grouping of units as we see fit, and the last two commits I pushed before this comment do exactly that.

**Comment by sraboy** [comment]
Sorry for the late reply. I feel like there was a specific reason I chose to have that repaint flag in the upper conditional but I may be confusing that with something else I did... possibly something completely unrelated. I don't have any comments in there so I'm gonna go with the latter since the nested conditional matches the structure in FirmFactory. This appears to work great.

And much thanks for knocking out the multiplayer part; I've actually never even played multiplayer 7K and I haven't had enough time to sit down and really dig in to understand it. Since I understand the sortie code now, this will be a fantastic reference for me.

On a side note, do we have a standard for code documentation beyond matching the current style? A lot of what you wrote above would be great to have documented next to the declarations and implementations; that's a big deep-dive on how/why for a seemingly insignificant object. I know we don't want change for the sake of change but using a standardized style that also works with various IDEs' code refactoring tools is incredibly handy when you're dug-in to some bit of code and can just hover the mouse over a variable to see its summary. It would be a nice touch for the long-term, especially for feature additions that require such extensive changes across the code.

**Comment by MicroVirus** [comment]
> .,. I feel like there was a specific reason I chose to have that repaint flag in the upper conditional ...
Hmm, well, if it comes to you let us know. Else, let's keep it like this for now.

> And much thanks for knocking out the multiplayer part; I've actually never even played multiplayer 7K and I haven't had enough time to sit down and really dig in to understand it. Since I understand the sortie code now, this will be a fantastic reference for me.

The basics of it is a message constant, e.g. `MSG_FIRM_MOBL_ALL_WORKERS`, a corresponding handler function, e.g. `RemoteMsg::mobilize_all_workers`, that is registered via `msg_process_function_array` and an actual game function to call, e.g. `Firm::mobilize_all_workers`.
The game function (`Firm::mobilize_all_workers`) needs to take at least an argument of `char remoteAction` to know if it's being called by the UI (player command), `COMMAND_PLAYER`, by the AI , `COMMAND_AI`, or via a multiplayer message `COMMAND_REMOTE`. It then starts with a check for `COMMAND_PLAYER`, in which case it queues the corresponding multiplayer message and exits (the multiplayer will then call the function again at a later time with `COMMAND_REMOTE` to actually execute it). That's the basic skeleton of a multiplayer message in 7kaa.


> On a side note, do we have a standard for code documentation beyond matching the current style?

Hmm, not really. The basic code documentation is done matching the same style as the current code, but that only captures the direct functionality of the function and its arguments. The post above is more of an overview of how things connect at a higher level. I guess the Wiki would be a decent place to put such things. I'm not sure if such higher-level views have a direct place as code comments.

**Comment by the3dfxdude** [comment]
> On a side note, do we have a standard for code documentation beyond matching the current style? A lot of what you wrote above would be great to have documented next to the declarations and implementations; that's a big deep-dive on how/why for a seemingly insignificant object. I know we don't want change for the sake of change but using a standardized style that also works with various IDEs' code refactoring tools is incredibly handy when you're dug-in to some bit of code and can just hover the mouse over a variable to see its summary. It would be a nice touch for the long-term, especially for feature additions that require such extensive changes across the code.

As a matter of reference, I really like how SDL and libenet does their documentation. SDL uses a wiki-like approach, where they link to the header files that are nicely and briefly documented, and then they detail more on the wiki page. libenet displays it is a similar way, but its all documented in code, and then extracted to be displayed on the web page.

I wrote up a simple request, stick to the code style, since I wanted consistency, and not someone putting alot of influence into a different style. Unfortunately, in the existing code base, you can tell that there was code written at different times, with different editors, probably some prior to 7K. The style gets a bit worse in 7K2 even when the code itself improved. And when we started, unfortunately a few new styles got introduced too, before I, and I'm sure the others really started get used to the existing unique style.

That said, you do bring up a point I've thought about. If you can propose a good way to do documentation, please do. For the time being though, I'll probably spend the time to enter my documentation on the wiki.

**Comment by the3dfxdude** [comment]
OK looks good to go.

I do want to mention two other minor things I mentioned in the original pull:
* Single soldiers can enter mine/factories and has an arrow indicating such. This seems like an odd thing to allow. Soldiers can't enter a seat of power, which does make sense. I think the behavior might change if they are in a team with a general.
* Seat of power overseers are not ejected with the mobilize button. I don't know the use of the mobilize button on a seat of power though. Maybe we should back that out.

These aren't really bad issues, likely already existing, but just odd.

**Pull request merged**
