### PR TITLE
Comment fixup

### PR DESCRIPTION
**Pull request by ralflang**
Seems like a copy/paste error in the function comments.

### CODE REVIEW

**Comment by MicroVirus** [comment]
The code is full of those errors. I usually try to sneak comment fixups into other code changes, because their impact is very minor.

**Comment by ralflang** [comment]
I understand and i'd like to commit more of this type, but no actual code changes yet - still getting into "the zone", finding what is where... Should I use this pull request to gather more documentation fixes?
I mean, they don't hurt compiling but it might help future committers to be less confused ...

**Comment by MicroVirus** [comment]
If you happen to come across confusing comments and fix them then you can add them to this pull request. I wouldn't actively go searching for them, though; that would be a bit of a waste of time.

the3dfxdude has the final say on it, but I think if you keep it short and to the point then at some point we can merge the comment fixups.

**Comment by the3dfxdude** [comment]
Pull requests for fixing a comment that is clearly wrong is okay. Just don't go overboard :)

Fixing spelling / minor grammar problems is not something I really want to see alot of, so fix those in a round about way.

**Pull request merged**
