### PR TITLE
Fix errors about const char* vs char*

### PR DESCRIPTION
**Pull request by cizra**

### CODE REVIEW

**Comment by the3dfxdude** [comment]
How do I reproduce an error? I see no issue with -Wall on gcc 5.3.0, and nothing wrong on visual inspection.

**Comment by MicroVirus** [comment]
I guess it's a, now deprecated, conversion allowed in C++ originally inherited from C, where string literals (`const char[N]`) can be implicitly converted to `char*`, rather than `const char*`.

Still, it'd be nice to know where the errors appeared and if we've got all of them.

**Comment by cizra** [comment]
https://pastebin.com/b93i3kaq -- here's the full build log with errors.

I'm building it on Mac, here's my GCC (actually clang):
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by the3dfxdude** [comment]
So I have clang/LLVM 3.8.0 here. You have 3.9.0svn. Apple LLVM version 8.0.0 (clang-800.0.42.1) is confusing, since there is no LLVM version 8. It's the version of Xcode. I doubt there are any real differences between my clang version and your version as far as I'm concerned.

The results when I run with clang are the same. I don't get any const char* -> char* errors. Can you share your log file from your failed run?

MicroVirus, I understand the issue, and we have required compliance for a long time now. The code in question looks fine when I scan through visually, and there are two compilers now that I have that don't seem to indicate a problem. Do you find any issue here with the code?

**Comment by the3dfxdude** [comment]
So the gnu gettext convenience header https://github.com/the3dfxdude/7kaa/commit/1203f158bbd535358f704e8a1a79c7818d8c3a68 has in the !ENABLE_NLS a purposeful cast to const char *. So even for things that could have been past through, it forces the restriction anyway. This is despite the return from the actual gettext. This raises questions in my mind, but the fixes look appropriate to use anyway.

**Comment by MicroVirus** [comment]
The [`gettext` manual](https://linux.die.net/man/3/gettext) mentions that the return type ought to be `const char*`, but isn't due to compatibility with pre-ANSI code, so indeed we should do the same and use the cast to `const char*` for non-NLS.

**Pull request merged**
