### PR TITLE
(WIP) Arabic Lang Support

### PR DESCRIPTION
**Pull request by Omaranwa**
as issue #107 i will start arabic lang and will wait for rtl support
this IS WORK IN PROGRESS DO NOT MERGE IT YET

### CODE REVIEW

**Comment by raz0rknaif** [comment]
.pot is a portable object template file. youre gonna want just the .po

**Comment by Omaranwa** [comment]
@raz0rknaif  ok i get it!

**Comment by raz0rknaif** [comment]
if you are using a text editor to edit this file, i suggest using a po editor. The gettext manual has a list of them. It makes things much easier.

For example, I noticed a couples things different in the header in my ar.po file such as pluals.

Is this standard Arabic? Or a dialect?

**Comment by Omaranwa** [comment]
@raz0rknaif this is standard Arabic
i am from egypt by the way.

**Comment by raz0rknaif** [comment]
Good luck.

Is there a way to contact you? Are you on the forums? This probably isn't the best place to carry on a conversation.

**Comment by the3dfxdude** [comment]
Please, no pull request for something not ready. You may work on your private branch and raz0rknaif until the time we can actually display the messages in game.

**Comment by Omaranwa** [comment]
@raz0rknaif If you use discord.
you can contact my on it
my tag is #8859

**Pull request closed without merging**
