### PR TITLE
Configurable backends for testing

### PR DESCRIPTION
**Pull request by MicroVirus**
Make all backends configurable (audio, ui (= mouse, vga), multiplayer) and add 'none' options for each.
This allows creating test applications. Most important for this is that the code supports different backends (though I guess it's a nice bonus then to also have it in the configure.ac).

This partially reverts the recent changes to the mouse and vga; sorry about that.

I actually have a first of such test applications that I've used to verify my changes to the saved game code (#96) in a more systematic way (and that even helped me find a bug in the original code). I want to commit that too at some point (it'd be one commit atop this list), though I haven't figured out a way to integrate 'make test' into the automake process yet.

### CODE REVIEW

**Comment by the3dfxdude** [comment]
Historically, VgaNone, and the other backends were used to stub out the windows code, and be able to compile on Linux. Then they were used as the starting point to write the current backends. The *None backends never actually worked for anything useful. (Although it might be the audio one did for a while, but VgaNone probably never did. MultiPlayer is trivial to avoid.) They were kept for a while, with the possibility that there could be a client-server architecture, but I decided client-server wasn't worth the trouble. Eventually, deeper integration with SDL led me to finally remove the backends as they were. They were useful during porting, but really have no purpose now, since you really couldn't switch after some changes were made.

Removal doesn't mean I don't want backends. I just don't want compile-time backends anymore. If backends are needed, I want them dynamically selected by the user at runtime. That's if we really need an option to switch. For testing purposes, configure-time backend selection seems problematic. I can't see how a 'make test' would work if a backed was already selected by configure.

For my own test applications, I think the approach I would want to use not to init whatever is not needed. So basically, to run without a window, I'd skip vga.init(), and then run what you need. But I know that SDL initialization is tied up into the Vga class, which creates a window. So for now I actually have added a "HEADLESS_SIM" compile flag, just to skip all the drawing. A few fixes probably can make this runnable in the same exe. I'm not sure about the audio.init(), but sure, why not, skip calling that as well.

A couple of these commits might be good cleanup. But abstracting away things through configure that we really will need to build the application seems too much.

**Comment by MicroVirus** [comment]
My goal was to get a test application for the saved games up and running as quickly as possible, hence I took the original route of having configure-time selection of backends to make it work.

I don't see how conditionally compiling code using compiler flags is going to be any different than the configure approach? These changes already use compiler flags to determine what backend to use, only then together with the configure changes to also only compile the files that are needed for that particular backend. Will compiling all files but only 'using' a particular set via compiler flags be better than what it is now?

**Comment by the3dfxdude** [comment]
I'm not suggesting to use compiler flags to build a test app. But I definitely don't want to go through configure twice to run different types of tests. My recommendation is that you should be able to build a test app within the current framework. That's what I do.

**Comment by the3dfxdude** [comment]
I pulled in a number of the changes, but we'll leave out the rest. I hope to make the backends more truly dynamic in the near future.

**Pull request closed without merging**
