### PR TITLE
Player Stats & Scenario Completion Tracking

### PR DESCRIPTION
**Pull request by sraboy**
Re: #52 
Hopefully I cherry-picked this right. I think I've worked out all the kinks so take a look and let me know what you think. There are a couple hack-ish things (some constantly re-used values like MAX_FILE_PATH that aren't globals) but those are across the code so I didn't touch those yet.

You can right-click on a scenario to cycle through the various checkboxes, allowing you to set/reset a particular scenario manually. Other than that, they're marked as played as soon as you launch one and marked complete if you finish a game without retiring.

This could probably be expanded to track training scenarios pretty easily too.

### CODE REVIEW

**Comment by the3dfxdude** [comment]
So I think I need to clarify something.

SaveGameInfo::MAX_FILE_PATH+1 is the size you want to use if you want to keep in sync with the file header. You ought to just store the filename in this record.

FilePath::MAX_FILE_PATH is what you should use if want to do path construction up to the defined maximum. It was split off from MAX_PATH and the SaveGameInfo because the maximum path length is a platform dependent maximum. In the future, FilePath class can be changed to respect each platform better, and do dynamic allocation instead.

Also, MAX_PATH was eliminated, because it was kind of abused.

It's up to you how you want to use the filename information from SaveGameInfo internally, but I would reference SaveGameInfo::MAX_FILE_PATH+1 as the field maximum.

Why did you switch to a binary file? I think ASCII or UTF-8 text is nicely portable & flexible. What if I want to store another kind of achievement?

**Comment by sraboy** [comment]
Thanks for clarifying the path stuff. The ScenInfo one is 260 chars even though it's always just the 8.3 file name but I store all 260 to keep it consistent with the SAV format's header. Plus it gives us flexibility if anyone ever releases third-party scenarios and uses that data for something.

I switched to binary because it's simpler. I just use `File.write_file`. It's pretty much the same as the hall of fame code but with a preceding record count. Adding a new type of achievement would be the same: just append on a record count followed by the array of data, and read that many records after reading scenarios or seeking past.

I can go back to text if you want but the File class makes it easier: a single line of code to read or write an entire array of records.

Long term, if we ever do a v3.0 with breaking changes, it would take 10min to just rollover HALLFAME.DAT into PLAYSTAT.DAT.

**Comment by the3dfxdude** [comment]
OK.

What's this "reserved_for_later"? I don't think we need to do that and it will waste space. If you want to be flexible, the format could be:

<header>
<size of record 1>
<count of record 1 array>
<record 1 array>
<size of record 2>
<count of record 2 array>
<record 2 array>
and so on.

And then you can just do your read_file up to the size that was stored, not exceeding the current structure size and if we added to the structure later, it would backwards and forwards compatible. (backwards compatibility is not a requirement though) Just remember to initialize the structure to something that works in case not all the data is available.

Then we just need to make sure to use portable enough structure packing.

This is the kind of stuff that the format for ReplayFile or SaveGame. Although I wish now SaveGame was simpler again for this reason.

**Comment by the3dfxdude** [comment]
BTW, I don't think it's necessary to typedef a struct in C++?

**Comment by sraboy** [comment]
Made all the recommended changes.

Does Linux have specific structure packing/alignment requirements on x86 that Windows doesn't, or are you considering additional architectures?

**Comment by the3dfxdude** [comment]
The structure packing is based on the compiler and how it targets the platform. The best approach I know of is to align the structure on every 4 bytes, and eliminate slop. I think we should use this here. This should not be hard to figure out. If you have gdb, use pahole. You can also use gcc -Wpadded to see what the compiler is doing. I don't know how to do this in Visual Studio, but it should respect any well packed structure the same.

**Comment by sraboy** [comment]
I just went with 1-byte alignment out of habit. You just want the members 4-byte aligned? Doesn't `#pragma pack(4)` do that? GCC supports that with the same behavior as VS, or am I missing something?

**Comment by the3dfxdude** [comment]
Er, I used pack(1) like you do on the old code, to make sure that there is no slop and changing alignment from the original non-optimized structures.

What I mean about aligning, is that instead of using any pack(), just pack the structure correctly from the beginning. Then the compiler doesn't change the alignment automatically on you causing issues, and there is no wasted space. I'll be using the mentioned tools to review, and check that everything is packed nicely on the 4 byte alignment.

http://www.catb.org/esr/structure-packing/

**Comment by sraboy** [comment]
Ooh I gotcha. I've gotten lazy about that. I'll need to swap ScenStat's status and internal names to get a natural alignment, and pad with a trailer char[3].  The Resource header is just three uint32_t's so that's fine.

**Comment by the3dfxdude** [comment]
You can make the file name length a multiple of 4. Like 256, or 260. 261 was a mistake in terms of WinAPI anyway.

**Comment by sraboy** [comment]
Okay, just went with 260 to keep it as close as possible to the SAV format. I removed the `pack()`s and just put in comment reminders about maintaining alignment.

**Comment by the3dfxdude** [comment]
Let me know if you are ready to have me start my pull review.

**Comment by sraboy** [comment]
I don't any more changes to make at the moment so feel free to get started whenever you're ready.

**Comment by the3dfxdude** [comment]
Please remember to update the Makefile for add/mv/del of files.

I merged it since it's mostly working and in good shape. But there is a bit of a bug somewhere. When you start the first scenario, Go Forth and Multiply, and exit back to main, the Prince Takao scenario gets checked as played too. The right click in the scenario menu doesn't seem to be linking them, so you have to check them off separately.

**Comment by sraboy** [comment]
Interesting. I remember running into that but thought I'd fixed it... maybe I cherry-picked the wrong commit or something.

**Comment by sraboy** [comment]
I was thinking of a different problem which was indeed fixed. It turns out there are several scenarios with duplicated internal names so they can't be tracked separately.

```
Real Name	|	Internal Name
----------------|-------------------
'SCN_06.SCN'	|	b'CHRI_002.SAV'
'INSULPOS.SCN'	|	b'insulpos.sav'
'VIKBLITZ.SCN'	|	b'WILL_004.SAV'
'NOTLOST.SCN'	|	b'S13__003.SAV'
'DESBOW.SCN'	|	b'scen12.sav'
'C&D.SCN'	|	b'UMBA_026.SAV'
'SCN_01.SCN'	|	b'KRUD_002.SAV'
'ERADICAT.SCN'	|	b'scen15.sav'
'SCN_12.SCN'	|	b'HARD_001.SAV'
'PIRATES.SCN'	|	b'GILB_001.SAV'
'MELTPOT.SCN'	|	b'S23__006.SAV'
'KUKULCNS.SCN'	|	b'YAXO_001.SAV'
'H&M.SCN'	|	b'scen03.sav'
'SCN_13.SCN'	|	b'ZOOL_003.SAV'
'MONORWAR.SCN'	|	b'scen07.sav'
'SCN_02.SCN'	|	b'KARI_001.SAV'
'SCN_08.SCN'	|	b'TUT__003.SAV'
'SCN_09.SCN'	|	b'OLAV_001.SAV'
'DESPERDO.SCN'	|	b'KARI_002.SAV'
'SCN_07.SCN'	|	b'CHIN_001.SAV'
'TREADCAR.SCN'	|	b'SCEN_014.SAV'
'RESDEP.SCN'	|	b'scen09.sav'
'SCN_04.SCN'	|	b'KARI_003.SAV'
'SCN_05.SCN'	|	b'AKBA_002.SAV'
'7FOR7.SCN'	|	b'TREV_004.SAV'
'IRONFIST.SCN'	|	b'u.sav\x0026.SAV'
'SCN_15.SCN'	|	b'LAST_003.SAV'
'PRNCTKAO.SCN'	|	b'KARI_001.SAV'
'FTFRAUTN.SCN'	|	b'TREV_006.SAV'
'MAKEBREK.SCN'	|	b'LEE__001.sav'
'SCN_10.SCN'	|	b'AGAM_002.SAV'
'NORMAN.SCN'	|	b'scen03.sav'
'SCN_11.SCN'	|	b'KUFU_001.SAV'
'SCN_14.SCN'	|	b'LOTS_001.SAV'
'WEAKENED.SCN'	|	b'u.sav\x0026.SAV'
'NEWWORLD.SCN'	|	b'LEIF_004.SAV'
'SCN_03.SCN'	|	b'KRSH_001.SAV'
'QUESUCCN.SCN'	|	b'scen03.sav'
```

There's the two you found (`KARI_001.SAV`), plus three `scen03.sav`, and two weird ones with `u.sav\x0026.SAV`. I see two fixes:

1. Update the binaries for the next release. Use unique internal names or just unique IDs.
2. (Hack) Recognize these few collisions when they're read and set a new & unique `SaveGame.game_name` value.

**Comment by the3dfxdude** [comment]
Why not just reset the internal name of the scn file on a load_scenario(), then record in playstat.dat using the corrected name. Now it will be an .scn extension when you save_game() as it has the correctly updated scenario name. Then load_game() will work fine, so you can continue to perform scenario completion tracking.

Then we don't have to worry about explaining to people that they need to rename the filename and the internal filename or tell people they need to use unique identifiers. Now to create a scenario, they will just have to rename the file with .scn extension.

**Comment by sraboy** [comment]
See #126. I assume that's what you meant, right?

**Pull request merged**
